In [1]:
# 라이브러리 모음
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import folium

In [30]:
# 데이터 불러오기
power_station = pd.read_excel('dataset/전라남도_신재생에너지 현황_20250623.xlsx')
power_station

,연번,허가번호,상호(발전소명),종류,발전소 주소,설비용량(킬로와트),허가일,개시일,데이터기준일자
0,1,전남제3호,대한소수력발전㈜(보성 소수력발전소),소수력,보성군 득량면 송곡리 1097-6,1200.00,2002-07-02,2009-03-03,2025-06-23
1,2,전남제13호,솔라플러스(주),태양광,"함평군 손불면 산남리 89-8,9,산111-1",1500.00,2004-04-02,2008-04-11,2025-06-23
2,3,전남제15호,에스디엔 주식회사(에스디엔 순천 태양광발전소),태양광,순천시 별량면 학산리 127-48외 9필지,1650.00,2004-05-18,2005-12-26,2025-06-23
3,4,전남제16호,한국농어촌공사 담양지사(담양호 소수력발전소),소수력,담양군 금성면 대성리 산5-3 일원,1274.00,2004-06-18,2006-07-01,2025-06-23
4,5,전남제20호,㈜지엔씨에너지(순천생활폐기물매립장 매립가스발전소),바이오에너지,순천시 왕지동 483-3(생활폐기물매립장),1850.00,2005-02-11,2005-07-29,2025-06-23
...,...,...,...,...,...,...,...,...,...
359,360,전남제4819호,와이제이솔라 주식회사(와이제이솔라 대평1호 태양광발전소),태양광,"경기도 용인시 기흥구 보정로 88, 101동 2003호(보정동, 죽현마을)",2500.00,2022-02-23,2022-12-15,2025-06-23
360,361,전남제4820호,효성솔텍(주)(효성광양금호 1호 태양광발전소),태양광,"서울특별시 서초구 효령로 304, 5074호(서초동, 국제전자센터)",2915.48,2022-02-23,2023-11-21,2025-06-23
361,362,전남제4827호,㈜광양솔라(도솔 태양광발전소),태양광,"경기도 의왕시 안양판교로 64, 4동 1002호",1285.83,2022-07-27,2023-12-12,2025-06-23
362,363,전남제4828호,(재)광양시사랑나눔복지재단(광양 복지형태양광발전소),태양광,전라남도 광양시 구마10길 25,1265.55,2022-07-27,2022-12-29,2025-06-23
363,364,전남제4862호,주식회사 디에스에너지(광양알루미늄 태양광발전소 1호),태양광,"전라남도 광양시 광양읍 인덕로 972,2층",2719.60,2022-11-08,2024-05-24,2025-06-23

In [ ]:
# '종류' 컬럼에서 "태양광" 값만 추출하기 
power_station = power_station[power_station['종류']=='태양광']
# 인덱스 번호 다시 부여하고 기존 인덱스 삭제
power_station = power_station.reset_index(drop=True)
# 인덱스 삭제
# del power_station['연번']
# del power_station['허가번호']
# del power_station['허가일']
# del power_station['데이터기준일자']
# del power_station['개시일']
# power_station.to_excel('전남발전소.xlsx')

PermissionError: [Errno 13] Permission denied: '전남발전소.xlsx'

In [55]:
power_station = pd.read_excel('전남발전소.xlsx')
power_station

,Unnamed: 0,상호(발전소명),종류,발전소 주소,설비용량(킬로와트),위도,경도
0,0,솔라플러스(주),태양광,"함평군 손불면 산남리 89-8,9,산111-1",1500.00,35.129207,126.445167
1,1,에스디엔 주식회사(에스디엔 순천 태양광발전소),태양광,순천시 별량면 학산리 127-48외 9필지,1650.00,NaN,NaN
2,2,에스디엔㈜(에스디엔 순천 태양광발전소),태양광,순천시 별량면 두고리 301-2,1000.00,NaN,NaN
3,3,한국수력원자력㈜(영광 솔라파크),태양광,"영광군 홍농읍 성산리 743,계마리966",3000.00,NaN,NaN
4,4,남해에너지개발㈜(남해태양광발전소),태양광,"강진군 신전면 용월리산255-15,26, 1",3000.00,NaN,NaN
...,...,...,...,...,...,...,...
347,347,와이제이솔라 주식회사(와이제이솔라 대평1호 태양광발전소),태양광,"경기도 용인시 기흥구 보정로 88, 101동 2003호(보정동, 죽현마을)",2500.00,NaN,NaN
348,348,효성솔텍(주)(효성광양금호 1호 태양광발전소),태양광,"서울특별시 서초구 효령로 304, 5074호(서초동, 국제전자센터)",2915.48,NaN,NaN
349,349,㈜광양솔라(도솔 태양광발전소),태양광,"경기도 의왕시 안양판교로 64, 4동 1002호",1285.83,NaN,NaN
350,350,(재)광양시사랑나눔복지재단(광양 복지형태양광발전소),태양광,전라남도 광양시 구마10길 25,1265.55,NaN,NaN
351,351,주식회사 디에스에너지(광양알루미늄 태양광발전소 1호),태양광,"전라남도 광양시 광양읍 인덕로 972,2층",2719.60,NaN,NaN

In [61]:
power_station['경도']=(
 126.404024,
 127.517605,
 127.551357,
 126.402621,
 126.503461,
 126.458098,
 126.495683,
 126.589368,
 126.570607,
 126.525783,
 126.318458,
 127.290929,
 127.286074,
 126.436089,
 126.602021,
 127.275718,
 127.012652,
 126.075075,
 126.085120,
 126.690318,
 126.475030,
 126.337495,
 126.653865,
 126.631324,
 126.510504,
 126.682958,
 126.493334,
 126.690560,
 126.468596,
 126.146897,
 127.356588,
 126.245850,
 126.382347,
 126.386494,
 126.564997,
 126.165643,
 126.811252,
 126.237282,
 127.375260,
 126.970351,
 126.507283,
 127.085945,
 127.088972,
 126.955238,
 126.913711,
 126.680037,
 127.374767,
 126.524598,
 126.997391,
 127.173655,
 127.105061,
 126.633237,
 127.457178,
 126.540292,
 127.375186,
 127.246209,
 126.275305,
 126.282148,
 127.093838,
 127.709614,
 127.139924,
 126.095835,
 126.593509,
 126.249872,
 126.096326,
 127.748254,
 127.723825,
 126.804736,
 126.253328,
 126.238980,
 126.260586,
 126.638387,
 126.633636,
 126.307982,
 126.664566,
 126.317357,
 126.631859,
 126.441337,
 126.442688,
 126.442264,
 127.655326,
 126.399578,
 126.457190,
 126.457282,
 126.399384,
 126.399445,
 126.612167,
 127.724057,
 127.026915,
 126.956554,
 126.638829,
 127.724235,
 127.114936,
 126.924312,
 127.508157,
 126.698392,
 126.698392,
 126.612054,
 126.420728,
 126.683400,
 127.281998,
 127.725994,
 126.586895,
 126.571185,
 126.698392,
 127.723096,
 126.634385,
 127.348278,
 127.145495,
 126.343057,
 126.342218,
 126.342218,
 126.405288,
 126.564783,
 126.654716,
 126.656400,
)
power_station['위도']=(
    35.131202,
    34.930409,
    34.934254,
    35.456885,
    34.600837,
    35.486318,
    34.569448,
    34.752641,
    34.396401,
    34.559297,
    35.068111,
    34.781468,
    34.772814,
    35.084222,
    34.575725,
    34.575422,
    35.051707,
    34.781180,
    34.794516,
    34.543260,
    34.505828,
    34.341750,
    34.717773,
    34.437070,
    35.100484,
    34.522378,
    34.507673,
    35.202704,
    34.480886,
    34.683221,
    34.533774,
    34.630634,
    34.523229,
    34.524732,
    34.758746,
    34.650314,
    35.062983,
    34.372831,
    34.528197,
    34.653483,
    34.299366,
    34.740220,
    34.739714,
    34.569315,
    34.576862,
    34.792651,
    34.528648,
    34.302217,
    34.490762,
    34.760504,
    34.742828,
    34.439156,
    34.930934,
    35.091498,
    34.538555,
    34.754399,
    34.390048,
    34.378126,
    34.717816,
    34.947815,
    34.607821,
    34.645620,
    34.513338,
    34.654432,
    34.645729,
    34.742814,
    34.953354,
    35.292345,
    34.631160,
    34.630634,
    34.631337,
    34.270443,
    34.285011,
    35.014231,
    35.318032,
    35.036821,
    34.284802,
    34.268030,
    34.267391,
    34.267458,
    34.896990,
    34.381040,
    34.483974,
    34.480737,
    34.381847,
    34.381763,
    35.115208,
    34.951454,
    35.184053,
    35.231608,
    34.296808,
    34.951510,
    35.018413,
    34.570762,
    34.880313,
    34.794975,
    34.794975,
    34.562653,
    35.461253,
    35.278500,
    35.104174,
    34.951091,
    34.487314,
    34.310823,
    34.794975,
    34.953385,
    34.283082,
    34.539735,
    34.559588,
    34.957668,
    34.958460,
    34.958460,
    34.533763,
    34.306491,
    35.240900,
    34.489317,
)

ValueError: Length of values (116) does not match length of index (352)